services:
  postgres-teslo:
    image: postgres:15.3
    container_name: teslo-db
    restart: always
    ports:
      - 5436:5432
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./postgres:/var/lib/postgresql/data

  # pdAdmin:
  #   image: dpage/pgadmin4:6.17
  #   container_name: pgadmin4
  #   restart: always
  #   depends_on:
  #     - my-database
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=alumno@google.com
  #     - PGADMIN_DEFAULT_PASSWORD=123456
  #   volumes:
  #     - ./pgadmin:/var/lib/pgadmin
  #     - ./pgadmin:/certs/server.cert
  #     - ./pgadmin:/certs/server.key
  #     - ./pgadmin:/pgadmin4/servers.json
