sonar.projectKey=EduardoMsf_for-fun
sonar.organization=eduardomsf

# Source code
sonar.sources=src

# Tests
sonar.tests=tests
sonar.test.inclusions=tests/**/*.test.ts,tests/**/*.test.tsx

# Coverage (from Vitest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Exclusions (VERY IMPORTANT for Next)
sonar.exclusions=node_modules/**,.next/**,coverage/**

sonar.sourceEncoding=UTF-8